services:
  db:
    image: mariadb:10.11.16
    container_name: fpvirtual-db
    restart: always
    profiles: ["with-db"]
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?Variable no definida}"
      MYSQL_DATABASE: "${MOODLE_DB_NAME:?Variable no definida}"
      MYSQL_USER: "${MOODLE_DB_USER:?Variable no definida}"
      MYSQL_PASSWORD: "${MOODLE_DB_PASSWORD:?Variable no definida}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fpvirtual-internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fpvirtual-redis
    restart: always
    networks:
      - fpvirtual-internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fpvirtual-moodle
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      MOODLE_DB_HOST: "${MOODLE_DB_HOST}"
      MOODLE_DB_PORT: "${MOODLE_DB_PORT}"
      MOODLE_DB_NAME: "${MOODLE_DB_NAME}"
      MOODLE_DB_USER: "${MOODLE_DB_USER}"
      MOODLE_DB_PASSWORD: "${MOODLE_DB_PASSWORD}"
      MOODLE_URL: "${MOODLE_URL}"
      MOODLE_ADMIN_USER: "${MOODLE_ADMIN_USER}"
      MOODLE_ADMIN_PASSWORD: "${MOODLE_ADMIN_PASSWORD}"
      MOODLE_ADMIN_EMAIL: "${MOODLE_ADMIN_EMAIL}"
      MOODLE_LANG: "${MOODLE_LANG}"
      MOODLE_SITE_NAME: "${MOODLE_SITE_NAME}"
      MOODLE_SITE_FULLNAME: "${MOODLE_SITE_FULLNAME}"
      SSL_PROXY: "${SSL_PROXY}"
      SMTP_HOSTS: "${SMTP_HOSTS}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_PASSWORD: "${SMTP_PASSWORD}"
      SMTP_MAXBULK: "${SMTP_MAXBULK}"
      NO_REPLY_ADDRESS: "${NO_REPLY_ADDRESS}"
      CRON_BROWSER_PASS: "${CRON_BROWSER_PASS}"
      INSTALL_TYPE: "${INSTALL_TYPE}"
      VERSION: "${VERSION}"
      FPVIRTUAL_PASSWORD: "${FPVIRTUAL_PASSWORD}"
      FPVIRTUAL_EMAIL: "${FPVIRTUAL_EMAIL}"
      MANAGER_PASSWORD: "${MANAGER_PASSWORD}"
      APP_PASSWORD: "${APP_PASSWORD}"
      APP_TEACHER_PASSWORD: "${APP_TEACHER_PASSWORD}"
      BLACKBOARD_URL: "${BLACKBOARD_URL}"
      BLACKBOARD_KEY: "${BLACKBOARD_KEY}"
      BLACKBOARD_SECRET: "${BLACKBOARD_SECRET}"
    volumes:
      - ./moodle-data:/var/www/moodledata
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fpvirtual-internal
      - moodle_network
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"

networks:
  fpvirtual-internal:
    driver: bridge
  moodle_network:
    external: true

volumes:
  db_data:
